Repository invisible-hands/frontend, pull requests merged in 2023-11, with the labels that each got.

#24 카카오 로그인 모달
  .gitignore
  package-lock.json
  package.json
  public/images/size-medium.svg
  src/App.jsx
  src/Auth.js
  src/ProtectedRoute.jsx
  src/components/LoginModal.jsx
  src/loginStore.js
  src/main.jsx
  src/modalStore.js
  src/pages/LoginPage.jsx
  src/pages/Redirection.jsx
Labels: 최진영, 프론트엔드

#25 [Feat] 헤더 푸터
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/assets/bettingground.png
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/LoginModal.jsx
  src/loginStore.js
  src/main.jsx
  src/modalStore.js
  src/pages/MainPage.jsx
  tailwind.config.js
Labels: 전지희, 프론트엔드

#26 Feat product
  .gitignore
  index.html
  package-lock.json
  package.json
  public/images/size-medium.svg
  src/App.jsx
  src/Auth.js
  src/ProtectedRoute.jsx
  src/assets/bettingground.png
  src/components/BidHistoryModal.jsx
  src/components/DeleteConfirmModal.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/LoginModal.jsx
  src/components/PaymentConfirmModal.jsx
  src/components/PaymentModal.jsx
  src/main.jsx
  src/pages/LoginPage.jsx
  src/pages/MainPage.jsx
  src/pages/ProductPage.jsx
  src/pages/Redirection.jsx
  src/queries/auctionQueries.js
  src/stores/loginStore.js
  src/stores/modalStore.js
  src/utils/timeUtils.js
  tailwind.config.js
Labels: 곽현준, 최진영, 전지희, 프론트엔드

#30 [Feat] 헤더 푸터 (최종)
  src/components/Footer.jsx
  src/components/Header.jsx
  src/main.jsx
Labels: 금방해유, 전지희, 프론트엔드

#29 Feat mypage
  .eslintrc.cjs
  .gitignore
  package-lock.json
  package.json
  public/harokIphone.png
  src/App.jsx
  src/components/AuctionRecord.jsx
  src/components/ComplainModal.jsx
  src/components/DropDown.jsx
  src/components/InvoiceInputModal.jsx
  src/components/PurchaseConfirmModal.jsx
  src/components/PurchaseItem.jsx
  src/components/PurchaseRecord.jsx
  src/components/SellingRecord.jsx
  src/components/ShoppingContainer.jsx
  src/components/Sidebar.jsx
  src/pages/MyShoppingPage.jsx
  src/stores/loginStore.js
Labels: 최진영, 프론트엔드

#31 [Feat] 메인 페이지 구현 (api 연결)
  package-lock.json
  package.json
  src/App.jsx
  src/assets/banner.jpg
  src/assets/detailBackground.jpg
  src/assets/sample.png
  src/components/Header.jsx
  src/components/ImageSlider.jsx
  src/components/ItemDetail.jsx
  src/components/preview/DeadlinePreview.jsx
  src/components/preview/HotPreview.jsx
  src/components/preview/NewPreview.jsx
  src/data/slidesData.js
  src/pages/MainPage.jsx
  src/pages/detail/DeadlineDetailPage.jsx
  src/pages/detail/HotDetailPage.jsx
  src/pages/detail/NewDetailPage.jsx
  src/pages/detail/SearchDetailPage.jsx
Labels: 전지희, 프론트엔드

#32 [Feat] 프로필 페이지 구현 (api 연결)
  package-lock.json
  package.json
  src/App.jsx
  src/assets/logo-square.png
  src/components/Sidebar.jsx
  src/pages/ProfilePage.jsx
Labels: 전지희, 프론트엔드

#33 Fix login
  package-lock.json
  package.json
  src/components/Header.jsx
  src/pages/Redirection.jsx
  src/stores/loginStore.js
Labels: 최진영, 프론트엔드

#35 [Feat] 프로필 페이지 사이드바 추가
  src/pages/ProfilePage.jsx
Labels: 금방해유, 전지희, 프론트엔드

#36 [Feat] 프로필 페이지 구현 (유효성검사 및 CSS 추가)
  .prettierrc.cjs
  src/components/Sidebar.jsx
  src/pages/ProfilePage.jsx
  src/stores/loginStore.js
Labels: 전지희, 프론트엔드

#37 [Feat] 메인페이지 구현 (로그아웃 로직 수정, CSS 추가)
  src/components/Header.jsx
  src/components/ImageSlider.jsx
  src/components/ItemDetail.jsx
  src/components/preview/DeadlinePreview.jsx
  src/components/preview/HotPreview.jsx
  src/components/preview/NewPreview.jsx
  src/pages/detail/SearchDetailPage.jsx
  src/stores/loginStore.js
Labels: 전지희, 프론트엔드

#38 [build] merge for krampoline
  .gitignore
Labels: 금방해유, 전지희, 프론트엔드

#39 Fix mypage
  package-lock.json
  package.json
  src/App.jsx
  src/components/AuctionRecord.jsx
  src/components/CustomDatePicker.jsx
  src/components/DropDown.jsx
  src/components/InvoiceInputModal.jsx
  src/components/PurchaseConfirmModal.jsx
  src/components/PurchaseItem.jsx
  src/components/PurchaseRecord.jsx
  src/components/SellingRecord.jsx
  src/components/ShoppingContainer.jsx
  src/pages/MyShoppingPage.jsx
Labels: 최진영, 프론트엔드

#42 [Fix] 프로필 페이지 닉네임 변경 validaton 수정
  src/pages/ProfilePage.jsx
Labels: 금방해유, 전지희, 프론트엔드

#45 [Fix] 24시간 오버플로우 수정
  src/components/ItemDetail.jsx
Labels: 오류발생, 금방해유, 전지희, 프론트엔드

#46 Fix bid
  .eslintrc.cjs
  .gitignore
  src/App.jsx
  src/components/BidHistory.jsx
  src/components/DeleteConfirmModal.jsx
  src/components/ItemDetail.jsx
  src/pages/AuctionPage/AuctionPage.jsx
  src/pages/AuctionPage/PaymentConfirmModal.jsx
  src/pages/AuctionPage/SellerInfo.jsx
  src/pages/AuctionRegisterPage/AuctionRegisterPage.jsx
  src/pages/BidPage/BidPage.jsx
  src/pages/SellerDetailPage.jsx
  src/queries/auctionQueries.js
Labels: 곽현준, 프론트엔드

#49 [Fix] 헤더 검색창 css 업데이트
  .env
  src/components/Header.jsx
Labels: 금방해유, 전지희, 프론트엔드

#50 [Feat] 검색/인기/마감/신상 페이지 css 업데이트 및 정렬 버튼 추가
  src/pages/detail/DeadlineDetailPage.jsx
  src/pages/detail/HotDetailPage.jsx
  src/pages/detail/NewDetailPage.jsx
  src/pages/detail/SearchDetailPage.jsx
Labels: 전지희, 프론트엔드

#51 Fix bid
  index.html
  src/App.jsx
  src/assets/payment_icon_yellow_medium.png
  src/assets/payment_icon_yellow_small.png
  src/components/BidHistory.jsx
  src/components/DeleteConfirmModal.jsx
  src/components/PaymentModal.jsx
  src/pages/AuctionPage/AuctionPage.jsx
  src/pages/AuctionPage/BidHistoryModal.jsx
  src/pages/AuctionPage/InstantPurchaseModal.jsx
  src/pages/AuctionPage/PaymentConfirmModal.jsx
  src/pages/AuctionPage/SellerInfo.jsx
  src/pages/AuctionRegisterPage/AuctionRegisterPage.jsx
  src/pages/BidPage/BidPage.jsx
  src/pages/PayResultPage.jsx
  src/pages/ProfilePage.jsx
  src/queries/auctionQueries.js
Labels: 곽현준, 프론트엔드

#53 Fix auction
  .eslintrc.cjs
  package-lock.json
  package.json
  src/pages/AuctionPage/AuctionPage.jsx
  src/pages/AuctionPage/SellerInfo.jsx
  src/pages/AuctionRegisterPage/AuctionImage.jsx
  src/pages/AuctionRegisterPage/AuctionRegisterPage.jsx
  src/pages/BidPage/BidPage.jsx
Labels: 금방해유, 곽현준, 프론트엔드

#54 [Fix] 이전 검색 결과 리셋
  src/pages/detail/SearchDetailPage.jsx
Labels: 오류발생, 금방해유, 전지희, 프론트엔드

#57 [Feat] 검색 input 에 엔터키 입력 이벤트 추가
  src/components/Header.jsx
Labels: 금방해유, 전지희, 프론트엔드, 해보고싶어요!

#59 [Bug] 경매가 종료되었는데도 경매 시간이 흐른다!?
  src/components/ItemDetail.jsx
Labels: 오류발생, 금방해유, 전지희, 프론트엔드

#60 fix: resolve DatePicker, MyShoppingPage, InvoiceModal bugs
  src/components/AuctionRecord.jsx
  src/components/CustomDatePicker.jsx
  src/components/PurchaseRecord.jsx
  src/components/SellingRecord.jsx
  src/pages/MyShoppingPage.jsx
Labels: 최진영, 프론트엔드

#61 Fix auction
  index.html
  src/components/BidSuccessModal.jsx
  src/components/DeleteConfirmModal.jsx
  src/components/PaymentModal.jsx
  src/pages/AuctionPage/AuctionPage.jsx
  src/pages/AuctionPage/BidHistoryModal.jsx
  src/pages/AuctionPage/InstantPurchaseModal.jsx
  src/pages/AuctionRegisterPage/AuctionRegisterPage.jsx
  src/pages/ProfilePage.jsx
  src/pages/SellerDetailPage.jsx
  src/utils/modalCloseUtils.js
Labels: 곽현준, 프론트엔드
